### ISSUE TITLE
请教下作者，这个插件以什么形式在直播姬上作为h5插件使用，另外，如果我想搭配OBS使用的话可以否指点一下？

### ISSUE THREAD

**Issue by wangpei72** [xiaoan-1/bilibili-ordersong-plugin#2]

**Comment by Aries277** [comment]
![image](https://github.com/xiaoan-1/bilibili-ordersong-plugin/assets/93179549/22a7d397-7a22-4d4a-8b67-efe2ecb79a47)
![image](https://github.com/xiaoan-1/bilibili-ordersong-plugin/assets/93179549/d45e82f6-14d1-4919-a0bf-3cbb34e6669a)
![image](https://github.com/xiaoan-1/bilibili-ordersong-plugin/assets/93179549/c75838ee-b144-4112-9c1e-2fffb891a972)

**Comment by xiaoan-1** [comment]
![image](https://github.com/xiaoan-1/bilibili-ordersong-plugin/assets/63486752/96f3abf2-16e7-4e8e-9625-370ff2c35d5d)

**Comment by wangpei72** [comment]
感谢。不过我其实想问的是怎么部署前端应用吧，我不知道这个插件url链接怎么获取。我目前使用tuna在OBS上实现了歌名获取，但是没有找到适合的歌词插件， 有时间我自己再去学一下吧。

**Comment by Ariesyc** [comment]
> > 感谢。不过我其实想问的是怎么部署前端应用吧，我不知道这个插件url链接怎么获取。我目前使用tuna在OBS上实现了歌名获取，但是没有找到适合的歌词插件， 有时间我自己再去学一下吧。
> 
> 请查看第二个分支，文档有公益链接可直接使用以及更详细的说明

第二个分支看不懂思密达，xiaoangeigei教教我
