### ISSUE TITLE
如何传入QQ音乐的cookie

### ISSUE THREAD

**Issue by MiKueYu** [xiaoan-1/bilibili-ordersong-plugin#4]
我已经在本地部署了[QQMusicApi](https://jsososo.github.io/QQMusicApi/#/?id=qqmusicapi)
但是我无法传入QQ音乐的cookie

**Comment by xiaoan-1** [comment]
QQ的API服务需要修改了一些代码和配置，你应该去[QQMusicApi](https://jsososo.github.io/QQMusicApi/#/?id=qqmusicapi)的作者issue那寻求解决方案
